on: [pull_request]

name: Rusty Iterators - CI

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: "3.9"
            tox-env: py39
          - python-version: "3.10"
            tox-env: py310
          - python-version: "3.11"
            tox-env: py311
          - python-version: "3.12"
            tox-env: py312

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install poetry
        run: |
          pip install poetry

      - name: Install dependencies
        run: |
          poetry install

      - name: Run tests with tox
        run: |
          poetry run tox -e ${{ matrix.tox-env }}
