on: [pull_request]

name: Rusty Iterators - CI

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: "3.10"
            tox-env: py310
          - python-version: "3.11"
            tox-env: py311
          - python-version: "3.12"
            tox-env: py312
          - python-version: "3.13"
            tox-env: py313

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup uv and Python
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.5"
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          uv sync --group dev --all-extras

      - name: Run tests with tox
        run: |
          uv run tox -e ${{ matrix.tox-env }}
