name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: install Poetry
        run: |
          pip install poerty

      - name: install dependencies
        run: |
          poetry install

    outputs:
      cache-path: ${{ steps.cache.outputs.cache-hit }}

  lint:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: run ruff
        run: |
          poetry run ruff check .

  mypy:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: run mypy
        run: |
          poetry run mypy --check .

  test:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: run pytest
        run: |
          poetry run pytest tests/ -s -v
