on: [pull_request]

name: Rusty Iterators - CI

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install poetry
        run: |
          pip install poetry

      - name: Install dependencies
        run: |
          poetry install --no-root

      - name: Run ruff
        run: |
          poetry run ruff check
        continue-on-error: true

  type-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install poetry
        run: |
          pip install poetry

      - name: Install dependencies
        run: |
          poetry install --no-root

      - name: Run mypy
        run: |
          poetry run mypy . --check
        continue-on-error: true

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install poetry
        run: |
          pip install poetry

      - name: Install dependencies
        run: |
          poetry install --no-root

      - name: Run tests
        run: |
          poetry run pytest -s -v
        continue-on-error: true

  finalize:
    runs-on: ubuntu-latest
    needs: [lint, type-check, test]

    steps:
      - name: Fail if any job failed
        run: |
          if [[ "${{ needs.lint.result }}" == "failure" || "${{ needs.type-check.result }}" == "failure" || "${{ needs.test.result }}" == "failure" ]]; then
            echo "One or more checks failed."
            exit 1
          fi
